Update deploy script to preserve local public

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,26 +2,46 @@
 HOST=brege.org
 DIR=/usr/share/nginx/brege.org/
 
-# Check for a valid Hugo installation
+# Check for a valid Hugo and webpack installation
 if ! which hugo > /dev/null; then
   echo "[hugo] Error: Hugo not found"
   exit 1
 fi
-
-# Check if the public directory exists
-if [ -d "public" ]; then
-  rm -rf public
+if ! which webpack > /dev/null; then
+  echo "[webpack] Error: webpack not found"
+  exit 1
 fi
 
-# Build hugo site:
+# this will be harmful to webpack build
+### Check if the public directory exists
+### if [ -d "public" ]; then
+###   rm -rf public
+### fi
+
+# Run webpack to build and bundle your JavaScript code
+echo "[webpack] Building JavaScript bundle..."
+webpack 2>&1 | awk '{print "[webpack]", $0}'
+
+# Check if the webpack build was successful
+if [ $? -ne 0 ]; then
+  echo "[webpack] Error: webpack build failed"
+  exit 1
+fi
+
+# Build hugo site
 echo "[hugo] Building site..."
 hugo --buildDrafts=false 2>&1 | awk '{print "[hugo]", $0}'
 
-# Check if the build was successful
+# Check if the hugo build was successful
 if [ $? -ne 0 ]; then
   echo "[hugo] Error: Hugo build failed"
   exit 1
 fi
+
+## Use html-minify to clean up HTML files 
+## # npm install html-minify
+## Maybe use this insted of sed/awk ....
+## find public/ -name "*.html" -exec node -e "const minify = require('html-minify').minify; minify(require('fs').readFileSync('{}', 'utf8'), { caseSensitive: true })" \;
 
 # Try to clean the whitespace and blank lines 
 # left by hugo logic
